### PR TITLE
website: change test image from lena to boat

### PR DESCRIPTION
**Pull request by phinze**
First of all, this is a really cool project! I love work like this that pushes the rules of a system to get unexpected and often beautiful results. :+1: :grinning: 

I was disappointed to scroll down to the examples to see the old-school [Lena Söderberg Playboy centerfold test image](https://en.wikipedia.org/wiki/Lenna) being used.

I understand the Playboy image has historically been a go-to for image processing demos, but I think in 2015 we can choose a demo that's a bit more inclusive than a nudie mag centerfold.

I chose [another test image from the SIPI database](http://sipi.usc.edu/database/database.php?volume=misc&image=14) and updated the website with the new image. I think the catalog looks just as sweet with the replacement image:

the_art_of_png_glitch

My favorite is that one in the center. :wink: 

Let me know if I messed up anything with the new test image - happy to reconvert or regenerate as necessary.

And once again, thanks for all your work on this project!

### CODE REVIEW

**Comment by rinopo** [comment]
:+1: Enlightening.

**Comment by ucnv** [comment]
Hi,
I knew the history of the Lena, and then decided to use it.
I respect oldschool hackers and their innocence like the case of Lena. I think their innocence is a part of their mind of hack.
Your issue is understandable. But this article is not about an education but a "glitch". I'd like to continue to use the Lena and its silliness.
Thanks anyway.

**Comment by phinze** [comment]
Hi @ucnv,

I understand your position, but I'd like to urge you to reconsider.

An article doesn't have to be specifically about education to make it worth avoiding something that's going to exclude/discourage people from enjoying it.

Even if you believe that the original folks who chose Lena were innocent, they were also all white dudes living in an era where a "slap on the butt" for a female coworker was much more common.

Today, I think you'd agree that slaps on the butt are totally out of line. I couldn't say "hey, back in the day people who did this were innocent, so therefore I am innocent!"

I believe it's the same thing here with choosing a nude Playboy centerfold as a test image.

We're in an industry with a _terrible_ track record for treatment of females. Every little bit we can do to make our space more welcoming is incredibly valuable to tell the dwindling number of females who chose to remain in tech: "yes, you are welcome here".

I've already put in all the work for you. I've chosen an image that comes from the same SIPI database, so it's still historically significant as a test image. All you have to do is click merge! :grinning:

**Comment by ucnv** [comment]
Interesting.
I've decided to reopen this so that I want to know more people's reaction for the Lena.
However it doesn't mean to merge phinze's alternatives because I do not fully agree with his logic (and just don't like the boat image).

**Comment by rodreegez** [comment]
:+1: for changing the image

**Comment by justincampbell** [comment]
Here's a recent article by someone with a different point of view than any of us have: https://www.washingtonpost.com/opinions/a-playboy-centerfold-does-not-belong-in-tj-classrooms/2015/04/24/76e87fa4-e47a-11e4-81ea-0649268f729e_story.html

I'm new to image processing, and was surprised to find this is the de facto test image.

**Comment by Charlotteis** [comment]
I definitely think we should change the image. It's the right thing to do and sets a good precedent.

**Comment by benhubbard434** [comment]
I agree with changing the image.

**Comment by dcarley** [comment]
@phinze and @justincampbell present some very good points. I think the image should be changed.

**Comment by nicolaiparlog** [comment]
:+1: for changing the image

I think the IT industry is a very complex system and many factors contribute to the exclusive and alienating patterns it currently demonstrates. These range from seemingly innocuous to outrageous. But it is hard to judge how a certain image (or statement, or policy, or ...) might affect a heterogeneous and largely anonymous crowd of users, participants, viewers, ... . The risk of alienating someone should be carefully weighed against the reasons for using said image (or whatever else we could be talking about).

In the case of demonstrating this cool library's features I can see how an image might be required to have certain technical properties. What it actually shows seems to be pretty unimportant. So if there are alternative images that do not contain the risk of contributing (however little) to the alienation of yet another female techie, I think it should be preferred.

PS: I also think that the boat image stinks.  :wink: Maybe a cool mountain range which does not look like a 70's ad?

**Comment by JoshCheek** [comment]
Changes like this only seem strange because they're change. If it went the other way, from a boat to a playboy centerfold, everyone would think "wtf?" I recognize that the image isn't inherently offensive, but it's derived from the paradigm of "boys only", and thus subtly reinforces those ideas. If we don't like the boat, then let's pick a different image that is more appealing. Once it's normal, it won't feel strange, and no one will have any desire to go back. As another example, imagine how strange it would feel if the image was of a guy in a magazine for women.

**Comment by phinze** [comment]
FWIW I'm happy to flip out the boat image - it was the one of the few color photos from the [SIPI Database](http://sipi.usc.edu/database/database.php) that seemed to have any range, and I was trying to maintain the "historical test image" aspect in case that was important. All those images do look like 70s ads though, since, y'know, they're from the 70s. :smile:

**Comment by AJFaraday** [comment]
It's definitely time to grow up about these things. If you're not going to also use a semi-naked man with a completely unattainable body shape then I suggest you move to the boat.

**Comment by eldang** [comment]
:+1: for changing the image.  Computing in general suffers from an enormous gender imbalance; signals like using a Playboy centerfold don't help, even when they were clearly not intended as anything harmful.

**Comment by nicolaiparlog** [comment]
Btw, @ucnv: big kudos for reopening this request! That should not be taken for granted and shows a lot of character. I wish more people were like that.

**Comment by ucnv** [comment]
In this discussion, I've become to further want to keep the Lena as the reflection of a ludicrousness of the human world. Yes it's irony for this request.
I do not want to make my work clean at all (I am a glitch artist, you know). Of course I will take any responsibility for my decision.
"The Art of PNG Glitch", people believe it is just a technical write up. But in reality it pretends to seem like that. It pretends the style of a tech paper but it doesn't say anything useful. It is a pastiche and the use of Lena is a part of that. I will say again that it is my "decision" though you might say that pastiche can't became a reason for the use of Lena. I intentionally did it.
I should notice that I made it as an art work rather than a write up. As an art work, sometimes, being controversial is nice because it can reflect a problem in the reality. I love this request.
Thank you

**Comment by ucnv** [comment]
I forgot to say;
In next chance to make some demos I will not use the Lena anymore. I think I have understood everybody's concern.
However in this case, I'm going to keep the initial design of the article. I explained why in the previous comment.

**Comment by phinze** [comment]
> I should notice that I made it as an art work rather than a write up. As an art work, sometimes, being controversial is nice because it can reflect a problem in the reality. I love this pull request.

> In next chance to make some demos I will not use the Lena anymore. I think I have understood everybody's concern. However in this case, I'm going to keep the initial design of the article.

I can understand and accept this reaction. The fact that you're willing to change your choice of test images in future projects I believe makes this PR a success. Thanks for being receptive to feedback and considerate of our larger tech community, @ucnv.

One last question, would you be willing to make a small link off to this pull request from the site? Perhaps if the Lena images silently linked off to this conversation? I think that might be a nice way for the work itself to acknowledge the complexity.

**Comment by ucnv** [comment]
@phinze OK, I've added a little comment on the bottom of the article. http://ucnv.github.io/pnglitch/#footer

**Comment by phinze** [comment]
@ucnv thanks for being receptive to this conversation, and once again great work on the project :grinning:

**Pull request closed without merging**
